Services = [
    "SDA Platform Agent Manager",
    "Hub Data Integration",
    "Agilent IO Libraries Service",
    "Agilent mDNS Responder Service",
    "Agilent PXI Resource Manager",
    "Hyper-V Virtual Machine Management",
    "ICBC Daemon Service",
    "ngSlotDaemon",
    "Offline Files",
    "Print Spooler",
    "Windows Phone IP over USB Transport (lpOverUsbSvc)",
    "Fax",
    "Google Update Service (gupdate)",
    "Google Update Service (gupdatem)",
    "Hyper-V Data Exchange Service",
    "Hyper-V Guest Service Interface",
    "Hyper-V Guest Shutdown Service",
    "Hyper-V Heartbeat Service",
    "Hyper-V Remote Desktop Virtualization Service",
    "Hyper-V Time Synchronization Service",
    "Hyper-V Volume Shadow Copy Requestor",
    "Remote Registry",
    "Remote Destop Configuration",
    "Remote Desktop Services",
    "Remote Desktop Services UserMode Port Redirector"
    # others searched from web
    "Windows Time",
    "Secondary Logon",
    "Routing and Remote Access Service",
    "BitLocker Drive Encryption Service",
    "Encrypting File System",
    "Certificate Propagation",
    "Microsoft iSCSI Initiator Service",
    "Netlogon",
    "Smart Card",
    "Smart Card Removal Policy",
    "Windows Connect Now",
    "Windows Firewall",
    "Windows Error Reporting Service",
    "Windows Defender",
    "Windows Media Center Receiver Service",
    "Windows Media Center Scheduler Service",
    "Windows Media Player Network Sharing Service",
    "HomeGroup Listener",
    "HomeGroup Provider",
    "Tablet PC Input Service",
    "IP Helper",
    "Network Access Protection Agent"]
